// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FFM_WIFI.Models.DataContext
{
    public partial class Player
    {
        public Player()
        {
            TeamPlayerAssignment = new HashSet<TeamPlayerAssignment>();
        }

        public int PlayerPk { get; set; }
        public string PlayerFirstName { get; set; }
        public string PlayerLastName { get; set; }
        public int PlayerAge { get; set; }
        public string PlayerDateOfBirth { get; set; }
        public string PlayerPosition { get; set; }
        public string PlayerNationality { get; set; }
        public string PlayerHeight { get; set; }
        public string PlayerImage { get; set; }

        public virtual ICollection<TeamPlayerAssignment> TeamPlayerAssignment { get; set; }
    }
}