// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FFM_WIFI.Models.DataContext
{
    public partial class Season
    {
        public Season()
        {
            SeasonLeagueTeamAssignment = new HashSet<SeasonLeagueTeamAssignment>();
            TeamPlayerAssignment = new HashSet<TeamPlayerAssignment>();
        }

        public int SeasonPk { get; set; }
        public string SeasonName { get; set; }

        public virtual ICollection<SeasonLeagueTeamAssignment> SeasonLeagueTeamAssignment { get; set; }
        public virtual ICollection<TeamPlayerAssignment> TeamPlayerAssignment { get; set; }
    }
}