// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FFM_WIFI.Models.DataContext
{
    public partial class UserPlayerAssignment
    {
        public int UsePlaUserFk { get; set; }
        public int UsePlaPlayerFk { get; set; }

        public virtual Player UsePlaPlayerFkNavigation { get; set; }
        public virtual User UsePlaUserFkNavigation { get; set; }
    }
}