// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseTesting.Models
{
    public partial class League
    {
        public League()
        {
            SeasonLeagueTeamAssignment = new HashSet<SeasonLeagueTeamAssignment>();
        }

        public int LeaguePk { get; set; }
        public string LeagueName { get; set; }
        public string LeagueLogo { get; set; }

        public virtual ICollection<SeasonLeagueTeamAssignment> SeasonLeagueTeamAssignment { get; set; }
    }
}