// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseTesting.Models
{
    public partial class SeasonLeagueTeamAssignment
    {
        public SeasonLeagueTeamAssignment()
        {
            TeamPlayerAssignment = new HashSet<TeamPlayerAssignment>();
        }

        public int SeaLeaTeaPk { get; set; }
        public int SeaLeaTeaSeasonFk { get; set; }
        public int SeaLeaTeaLeagueFk { get; set; }
        public int SeaLeaTeaTeamFk { get; set; }

        public virtual League SeaLeaTeaLeagueFkNavigation { get; set; }
        public virtual Season SeaLeaTeaSeasonFkNavigation { get; set; }
        public virtual Team SeaLeaTeaTeamFkNavigation { get; set; }
        public virtual ICollection<TeamPlayerAssignment> TeamPlayerAssignment { get; set; }
    }
}