// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseTesting.Models
{
    public partial class UserTeamPerformance
    {
        public int UserTeamPerformancePk { get; set; }
        public int UserTeamPerformanceGk1 { get; set; }
        public int UserTeamPerformanceDf1 { get; set; }
        public int UserTeamPerformanceDf2 { get; set; }
        public int UserTeamPerformanceDf3 { get; set; }
        public int UserTeamPerformanceDf4 { get; set; }
        public int UserTeamPerformanceMf1 { get; set; }
        public int UserTeamPerformanceMf2 { get; set; }
        public int UserTeamPerformanceMf3 { get; set; }
        public int UserTeamPerformanceMf4 { get; set; }
        public int UserTeamPerformanceAt1 { get; set; }
        public int UserTeamPerformanceAt2 { get; set; }
        public int UserTeamPerformanceGk2 { get; set; }
        public int UserTeamPerformanceDf5 { get; set; }
        public int UserTeamPerformanceMf5 { get; set; }
        public int UserTeamPerformanceMf6 { get; set; }
        public int UserTeamPerformanceAt3 { get; set; }
        public int UserTeamPerformanceAt4 { get; set; }
        public int UserTeamPerformanceUserTeamFk { get; set; }
    }
}